# Generated by Django 2.1.3 on 2018-12-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_comment', models.CharField(max_length=1000)),
                ('A_date', models.CharField(max_length=50)),
                ('A_tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.Teachers')),
            ],
        ),
    ]
