# Generated by Django 2.1.3 on 2018-12-12 14:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_students_s_cgpa'),
        ('Teacher', '0002_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatewiseAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Students')),
            ],
        ),
        migrations.CreateModel(
            name='finalAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Students')),
            ],
        ),
    ]
