# Generated by Django 2.1.3 on 2018-12-01 18:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='books/pdfs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('C_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('C_name', models.CharField(max_length=15)),
                ('C_credits', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('S_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('S_name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('S_email', models.EmailField(blank=True, default='farazuddin.m17@iiits.in', max_length=254)),
                ('S_password', models.CharField(max_length=50)),
                ('S_courses', models.ManyToManyField(to='Student.Courses')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='B_cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Courses'),
        ),
    ]
