# Generated by Django 2.1.2 on 2018-12-07 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_auto_20181207_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assign_marks',
            new_name='AssignMarks',
        ),
        migrations.AlterField(
            model_name='gradingpolicy',
            name='G_weightage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
