# Generated by Django 2.1.3 on 2018-12-11 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_auto_20181212_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalgradepolicy',
            name='F_course',
        ),
        migrations.RemoveField(
            model_name='finalmarks',
            name='F_course',
        ),
        migrations.RemoveField(
            model_name='finalmarks',
            name='F_sid',
        ),
        migrations.DeleteModel(
            name='FinalGradePolicy',
        ),
        migrations.DeleteModel(
            name='FinalMarks',
        ),
    ]
