# Generated by Django 2.1.3 on 2018-12-11 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_auto_20181212_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGradePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_s', models.IntegerField(default=0)),
                ('F_a', models.IntegerField(default=0)),
                ('F_b', models.IntegerField(default=0)),
                ('F_c', models.IntegerField(default=0)),
                ('F_d', models.IntegerField(default=0)),
                ('F_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='FinalMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_marks', models.FloatField(default=0)),
                ('F_grade', models.CharField(default='F', max_length=1)),
                ('F_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Courses')),
                ('F_sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Students')),
            ],
        ),
    ]
