# Generated by Django 2.1.3 on 2018-11-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='C_books',
            field=models.ManyToManyField(blank=True, to='Student.Book'),
        ),
    ]
