# Generated by Django 2.1.3 on 2018-11-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_auto_20181127_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='Book_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
